server:
  port: 10005

spring:
  application:
    name: service-message

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 192.168.159.138
    port: 6379
    database: 0
    timeout: 2000000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

  rabbitmq:
    host: 192.168.159.138
    username: admin
    password: 123
    port: 5672

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8