server:
  port: 10003

spring:
  application:
    name: service-front

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: fqh

  redis:
    host: 192.168.159.138
    port: 6379
    database: 0
    timeout: 2000000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        #配置Sentinel Dashboard地址
        dashboard: localhost:8080
        port: 8719
        #持久化流控规则
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: service-front
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

feign:
  sentinel:
    enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/fqh/front/mapper/xml/*.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
